Improved_window.application
kandiana/skypro_project-1_team-4 pull request #14
Opened 2021-09-28 16:37 UTC by MariaBabintseva

2021-09-28 16:50 UTC, slepovsde submitted a review, later dismissed
/ok

2021-09-28 17:24 UTC, AlexRaevskiy reviewed
Почему тыв 12 строчке решила использовать document.getElementById, а не document.querySelector?

2021-09-28 17:32 UTC, MariaBabintseva commented
Да, спасибо, не увидела, видимо старая версия загрузилась)

2021-09-28 17:34 UTC, AlexRaevskiy approved these changes, later dismissed
/ok

2021-09-28 19:12 UTC, kandiana requested changes
Я тут подумала, что стоит сначала проверять, существует ли страница, а очищать, только если она существует. 

Сейчас, если страницы не существует, появится белый экран.
А так останется старая страница.

И лучше прокомментировать строчку с очисткой экрана.

Ну и возврат создаваемого блока можно сразу вставить (:

2021-09-29 07:18 UTC, kandiana approved these changes
/ok

2021-09-29 07:25 UTC, slepovsde approved these changes

2021-09-29 08:02 UTC, merged