Added screen move
kandiana/skypro_project-1_team-4 pull request #19
Opened 2021-09-29 15:21 UTC by MariaBabintseva

2021-09-29 21:13 UTC, kandiana requested changes
> функция renderBlockScreenTitle

У нас на каждой странице будет заголовок, поэтому текст в него надо вставлять в функции отрисовки экрана, а не в отрисовке блока. И даже если бы это было не так, все равно стоит везде возвращать отрисованный блок (должен быть return blockName)

И я бы слово Block из названия убрала... Ты его, я так понимаю, добавила, так как у меня есть такая же функция. Поэтому у нас сейчас в программе происходит переопределение: сначала устанавливается 
window.application.blocks['screenTitle'] = renderScreenTitle
а потом переписывается
window.application.blocks['screenTitle'] = renderBlockScreenTitle

По этой причине я хочу в конце все функции отрисовки блоков собрать в один файл, чтобы не было дубликатов.

> функция renderButton
У всех кнопок должен быть класс button, чтобы мы могли их однообразно (и без копипаста) стилизовать.

> Названия классов
Я бы не стала вписывать в кнопки классы с названиями 'rock', 'paper', 'scissors' и опираться при нажатии на них. Ведь классов может быть несколько. В частности у кнопок гарантированно должен быть класс button. 
Ключевые слова 'rock', 'paper', 'scissors' скорее надо указать в одном из data-параметров, например, data-name или data-id

> Двойные кавычки у ["game-status"]
В js лучше везде иметь одинарные.

Вроде, все :)

2021-09-30 08:58 UTC, kandiana requested changes
> изменения в request файле

Их в этом ПР'е быть не должно. Проверь, что ты правильно подтянула мастер ветку и перебазировала свою на нее:
git switch master
git pull --rebase origin master
git switch your-branch
git rebase master

> дата-атрибуты

Почитай статью про то, как они используются:
https://developer.mozilla.org/ru/docs/Learn/HTML/Howto/Use_data_attributes
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

Их не надо сохранять в отдельные переменные, их надо просто задать через dataset и потом точно так же у target'а вытащить.

> константы player и game

Я переместила их в window.application
Буду признательна, если ты примешь ПР и заменишь все обращения к этим переменным у себя сама (иначе это придется делать мне после мержа твоего ПР'а)

2021-09-30 10:33 UTC, slepovsde submitted a review, later dismissed

2021-09-30 11:36 UTC, kandiana approved these changes
/ok

2021-09-30 11:55 UTC, slepovsde approved these changes

2021-09-30 11:55 UTC, merged

2021-09-30 12:16 UTC, AlexRaevskiy reviewed
/ok