Maria.waiting for enemy screen
kandiana/skypro_project-1_team-4 pull request #20
Opened 2021-09-29 17:39 UTC by MariaBabintseva

Экран ожидания игры, пока без стилей

2021-09-29 21:41 UTC, kandiana requested changes
Лучше, чтобы поле token у игрока не было пустым, иначе все запросы будут падать с ошибкой (там только пинг и логин делаются без токена).

> function renderBlockLoading(container) {
>    const text = document.createElement('h1')
>    text.classList.add('text')

Лучше тут класс не text добавлять, а loading. У нас могут быт другие строки текста, а этот блок не всегда будет текстовым (я надеюсь)

> if (data["game-status"].status !== 'waiting-for-start') {
>     window.application.renderScreen('playScreen')
>   }

Мне кажется, логичнее, если условие будет одним из двух вариантов:
1. 
```
if (data["game-status"].status !== 'waiting-for-start') {
     window.application.renderScreen('playScreen')
   }
```
   
То есть мы отрисовываем блок хода если нам пришел соответствующий статус, а не если мы больше не находимся на экране ожидания.
2. 
```
if (data["game-status"].status === 'waiting-for-start') {
     return
   }
   window.application.renderScreen('playScreen')
```

То есть если мы все еще ждем соперника, то ничего не происходит.
А если мы его уже не ждем, то переходим дальше.

2021-09-30 08:59 UTC, kandiana approved these changes, later dismissed
/ok

только тебе еще изменения от мастера подтянуть надо...

2021-09-30 10:26 UTC, kandiana approved these changes
/ok

2021-09-30 10:27 UTC, slepovsde approved these changes
/ok

2021-09-30 10:38 UTC, merged