Implemented window.application, renderScreen, renderBlock functions
kandiana/skypro_project-1_team-4 pull request #9
Opened 2021-09-27 16:00 UTC by MariaBabintseva

2021-09-27 20:39 UTC, kandiana requested changes
**По поводу решения конфликта: Саша просил не делать это через merge, а делать это через rebase.**

Имеет смысл:
1. Откатить ветку в состояние исходного pull request'а: 

- git log покажет историю коммитов, там можно найти их хэш-коды 
- git reset [хэш-код] позволит откатиться к выбранному коммиту. Тут надо сначала найти тот, который исходно был в этом ПР.

2. Выполнить rebase, как нас и просили:

- переключиться на ветку master и притянуть в нее изменения (git pull)
- переключиться на свою ветку и прописать git rebase master
- решить все конфликты
- прописать git add . и git rebase --continue
- и наконец git push -f

Пиши вопросы, если эти действия непонятны, ибо я сама в них не очень уверена, пока еще этим не занималась :) Надо пробовать.

**По самому коду**

Строка 21
`//Проверяем сущиствует ли страница, которую передаем в функцию`
сущЕствует
В VSC можно установить проверку орфографии, тогда такие ошибки будут сразу подчеркиваться. Можем завтра обсудить, как это делается.

Строка 22
`if (window.application.screens[screenName] === undefined)`
Это эквивалентно такой записи:
if (window.application.screens[screenName])
Потому что undefined - это falsy

По очищению массива таймеров:
1. Как думаешь, логичнее сначала нарисовать новый экран, а потом очистить массив старого экрана или наоборот, сначала очистить массив, а потом нарисовать новый экран?
2. Протестируй такой случай: создай два-три глобальных таймера, добавь их в массив, запусти функцию очистки, а после уже проверь, все таймеры очистились или нет. 
3. Мне кажется, полезно не только сами таймеры очищать, но и переменные, в которых хранятся их id тоже. Это можно сделать приравниванием timer к undefined после очистки.

Круто, что добавила примеры! Это реально удобно и позволяет быстрее разобраться в коде.

2021-09-28 06:09 UTC, slepovsde approved these changes, later dismissed

2021-09-28 08:49 UTC, kandiana requested changes
Я не до конца понимаю, как это работает (видимо, на моменте инициализации цикла на 21 строке `for (let timer of window.application.timers)` создается копия массива, надо почитать), но все равно нехорошо очищать массив внутри цикла.

Вынеси очистку за пределы цикла, пусть массив очищается, когда все таймеры были очищены и удалены.

В остальном все хорошо!

2021-09-28 08:49 UTC, slepovsde submitted a review, later dismissed
Хочу увидеть это в действии.

2021-09-28 10:59 UTC, kandiana submitted a review, later dismissed
/ok

2021-09-28 11:05 UTC, slepovsde submitted a review, later dismissed
/ok

2021-09-28 11:29 UTC, kandiana approved these changes
/ok

2021-09-28 11:30 UTC, slepovsde approved these changes
/ok

2021-09-28 11:31 UTC, merged